-- =========================================================
-- Library Management System - ORACLE VERSION
-- Run this as your library schema user (not as SYS/SYSTEM)
-- =========================================================

-- ---------------------------------------------------------
-- STEP A (run once, as SYS, if you don't have a schema yet):
-- ---------------------------------------------------------
-- sqlplus sys/your_sys_password@localhost:1521/XEPDB1 as sysdba
--
-- CREATE USER library_admin IDENTIFIED BY library123;
-- GRANT CONNECT, RESOURCE, CREATE VIEW, UNLIMITED TABLESPACE TO library_admin;
--
-- Then reconnect as library_admin and run everything below:
-- sqlplus library_admin/library123@localhost:1521/XEPDB1

-- ---------------------------------------------------------
-- Drop old objects if re-running this script
-- ---------------------------------------------------------
BEGIN EXECUTE IMMEDIATE 'DROP TABLE transactions CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE books CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE members CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE admin'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- ---------------------------------------------------------
-- TABLE: admin
-- ---------------------------------------------------------
CREATE TABLE admin (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50) NOT NULL UNIQUE,
    password VARCHAR2(100) NOT NULL
);

INSERT INTO admin (username, password) VALUES ('admin', 'admin123');

-- ---------------------------------------------------------
-- TABLE: books
-- ---------------------------------------------------------
CREATE TABLE books (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    isbn VARCHAR2(20) NOT NULL UNIQUE,
    title VARCHAR2(200) NOT NULL,
    author VARCHAR2(150) NOT NULL,
    publisher VARCHAR2(150),
    category VARCHAR2(100),
    publication_year NUMBER(4),
    quantity NUMBER NOT NULL,
    available_quantity NUMBER NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ---------------------------------------------------------
-- TABLE: members
-- ---------------------------------------------------------
CREATE TABLE members (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id VARCHAR2(20) NOT NULL UNIQUE,
    full_name VARCHAR2(150) NOT NULL,
    email VARCHAR2(150) NOT NULL UNIQUE,
    phone VARCHAR2(15),
    gender VARCHAR2(10),
    course VARCHAR2(100),
    semester VARCHAR2(20),
    address VARCHAR2(255),
    registration_date DATE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ---------------------------------------------------------
-- TABLE: transactions
-- ---------------------------------------------------------
CREATE TABLE transactions (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id NUMBER NOT NULL,
    book_id NUMBER NOT NULL,
    issue_date DATE NOT NULL,
    due_date DATE NOT NULL,
    return_date DATE,
    fine NUMBER(10,2) DEFAULT 0,
    status VARCHAR2(20) DEFAULT 'ISSUED' NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_trans_member FOREIGN KEY (member_id) REFERENCES members(id) ON DELETE CASCADE,
    CONSTRAINT fk_trans_book FOREIGN KEY (book_id) REFERENCES books(id) ON DELETE CASCADE
);

-- ---------------------------------------------------------
-- SAMPLE BOOKS (Oracle needs one INSERT per row, no multi-row VALUES)
-- ---------------------------------------------------------
INSERT INTO books (isbn, title, author, publisher, category, publication_year, quantity, available_quantity) VALUES ('978-0134685991', 'Effective Java', 'Joshua Bloch', 'Addison-Wesley', 'Programming', 2018, 5, 5);
INSERT INTO books (isbn, title, author, publisher, category, publication_year, quantity, available_quantity) VALUES ('978-0596009205', 'Head First Design Patterns', 'Eric Freeman', 'O''Reilly Media', 'Programming', 2004, 4, 4);
INSERT INTO books (isbn, title, author, publisher, category, publication_year, quantity, available_quantity) VALUES ('978-0132350884', 'Clean Code', 'Robert C. Martin', 'Prentice Hall', 'Programming', 2008, 3, 3);
INSERT INTO books (isbn, title, author, publisher, category, publication_year, quantity, available_quantity) VALUES ('978-0071392319', 'Database System Concepts', 'Abraham Silberschatz', 'McGraw-Hill', 'Database', 2010, 6, 6);
INSERT INTO books (isbn, title, author, publisher, category, publication_year, quantity, available_quantity) VALUES ('978-0262033848', 'Introduction to Algorithms', 'Thomas H. Cormen', 'MIT Press', 'Computer Science', 2009, 4, 4);
INSERT INTO books (isbn, title, author, publisher, category, publication_year, quantity, available_quantity) VALUES ('978-0134494166', 'Clean Architecture', 'Robert C. Martin', 'Prentice Hall', 'Programming', 2017, 2, 2);
INSERT INTO books (isbn, title, author, publisher, category, publication_year, quantity, available_quantity) VALUES ('978-9332555316', 'Operating System Concepts', 'Abraham Silberschatz', 'Wiley', 'Computer Science', 2014, 3, 3);
INSERT INTO books (isbn, title, author, publisher, category, publication_year, quantity, available_quantity) VALUES ('978-0201633610', 'Design Patterns', 'Erich Gamma', 'Addison-Wesley', 'Programming', 1994, 2, 2);

-- ---------------------------------------------------------
-- SAMPLE MEMBERS
-- ---------------------------------------------------------
INSERT INTO members (member_id, full_name, email, phone, gender, course, semester, address, registration_date) VALUES ('MEM1001', 'Aarav Sharma', 'aarav.sharma@example.com', '9876543210', 'Male', 'B.Tech CSE', '5', 'Ahmedabad, Gujarat', TO_DATE('2026-01-10','YYYY-MM-DD'));
INSERT INTO members (member_id, full_name, email, phone, gender, course, semester, address, registration_date) VALUES ('MEM1002', 'Priya Patel', 'priya.patel@example.com', '9876500001', 'Female', 'BCA', '3', 'Surat, Gujarat', TO_DATE('2026-02-15','YYYY-MM-DD'));
INSERT INTO members (member_id, full_name, email, phone, gender, course, semester, address, registration_date) VALUES ('MEM1003', 'Rohan Mehta', 'rohan.mehta@example.com', '9876500002', 'Male', 'M.Sc IT', '2', 'Vadodara, Gujarat', TO_DATE('2026-03-05','YYYY-MM-DD'));
INSERT INTO members (member_id, full_name, email, phone, gender, course, semester, address, registration_date) VALUES ('MEM1004', 'Sneha Joshi', 'sneha.joshi@example.com', '9876500003', 'Female', 'B.Tech IT', '7', 'Rajkot, Gujarat', TO_DATE('2026-01-22','YYYY-MM-DD'));

-- ---------------------------------------------------------
-- SAMPLE TRANSACTION (one already issued, for testing return/fine)
-- ---------------------------------------------------------
INSERT INTO transactions (member_id, book_id, issue_date, due_date, return_date, fine, status)
VALUES (1, 1, TO_DATE('2026-09-01','YYYY-MM-DD'), TO_DATE('2026-09-08','YYYY-MM-DD'), NULL, 0, 'ISSUED');

UPDATE books SET available_quantity = available_quantity - 1 WHERE id = 1;

COMMIT;

-- Verify
SELECT * FROM admin;
SELECT * FROM books;
SELECT * FROM members;
SELECT * FROM transactions;
